mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('comments/', views.CommentsView.display, name='comments'),
    path('comments/list/', views.display_list, name='list')
]

polls/models.py
from django.db import models

from django.utils import timezone
import datetime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now 
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Comment(models.Model):
    comment_text = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    #pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.comment_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.http import Http404
from django.views import generic 
from django.utils import timezone


from .models import Choice, Question, Comment

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/question_detail.html'
    def get_queryset(self):
        """
        Excludes any questions taht aren't published yet
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/question_detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


class CommentsView(generic.TemplateView):
    model = Comment
    template_name = 'polls/comments.html'

    def display(request):
        if (request.method == "POST"):
            name = request.POST.get('name')
            comment_text = request.POST.get('comment')
            new_comment = Comment(name = name, comment_text = comment_text) 
            new_comment.save()
            return HttpResponseRedirect(reverse('polls:list'))
        return render(request, 'polls/comments.html')


def display_list(request):
    context = {
        'comments': Comment.objects.all(),
        'latest_question': Question.objects.filter(pub_date__lte=timezone.now()).last()
      }
    return render(request, 'polls/list.html', context)

polls/templates/polls/comments.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head> 

<!-- Navbar-->
<nav class="navbar navbar-expand-lg nav-bg">
    <a class="navbar-brand font-white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link font-white" href="#">Current Poll <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class=" font-white nav-link font-white" href="#">Comments</a>
        </li>
        <li class="nav-item dropdown">
          <a class=" font-white nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Past Polls
          </a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

<!-- Comment Form-->
<body>
    <div class="mt-4 container d-flex justify-content-center flex-column mb-5 ">
        <div class= "pt-4 d-flex justify-content-center text-left">
            <form class = "p-5 comment-list" action="{% url 'polls:comments' %}" id="comment" method="post">
                {% csrf_token %}

                <h1 class = "pb-3">Add a comment: </h1>

                <div class = "mb-3 ">
                    <div class="">
                        <h3>Name </h3>
                        <input type="text" class="form-control" name="name">
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <div class="form-group">
                        <h3>Comment </h3>
                        <textarea name="comment" rows="5" cols="50" placeholder="Type comment here..."></textarea>
                    </div>
                </div>

                <div>
                    <button type="submit" class="btn btn-primary" style="margin: auto;">Make Comment</button>
                </div>

            </form>
        </div>
    </div>


    <!-- Footer -->

<div class = "mt-5 pt-5 pb-3 footer">
    <div style="color: white" class = "">
      <div class = "d-flex row text-center">

        <div class="col-3">
          <h6>Subscribe to our Newsletter</h6>
          <h6>Learn More</h6>
        </div>

        <div class="col-6">
          <h6>Created by Jett Bisset</h6>
          <p style="font-size: 12px;">All Rights Reserved</p>
        </div>

        <div class="col-3">
          <h6>Privacy</h6>
          <h6>About Us</h6>
        </div>

      </div>
    </div>
  </div>
</body>

polls/templates/polls/index.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<bod>
<!-- Navbar-->
<nav class="navbar navbar-expand-lg nav-bg">
    <a class="navbar-brand font-white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link font-white" href="#">Current Poll <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class=" font-white nav-link font-white" href="#">Comments</a>
        </li>
        <li class="nav-item dropdown">
          <a class=" font-white nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Past Polls
          </a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
</nav>


  <div class="mt-4 container d-flex justify-content-center flex-column ">
    <div class= "pt-4 d-flex justify-content-center text-left">

{% if latest_question_list %}
    <div class="mt-4 container d-flex justify-content-center flex-column">
      <div class= "comment-list pt-4 d-flex text-center flex-column justify-content-center">

        <h1 class = "pl-4">Current Polls:</h1>
        <ul>
            {% for question in latest_question_list %}
            <li style ="list-style: none">
                <a class ="font" href="{% url 'polls:detail' question.id %}">{{ question.question_text }}
                </a>
            </li> 
            {% endfor %}
        </ul>
      </div>
    </div>
  </div>
</div>  



{% else %}
    <p>No polls are available.</p>
{% endif %}


<!-- Footer -->

<div style="position: fixed" class = "mt-5 pt-5 pb-3 footer">
  <div style="color: white" class = "">
    <div class = "d-flex row text-center">

      <div class="col-3">
        <h6>Subscribe to our Newsletter</h6>
        <h6>Learn More</h6>
      </div>

      <div class="col-6">
        <h6>Created by Jett Bisset</h6>
        <p style="font-size: 12px;">All Rights Reserved</p>
      </div>

      <div class="col-3">
        <h6>Privacy</h6>
        <h6>About Us</h6>
      </div>

    </div>
  </div>
</div>

</body>

polls/templates/polls/list.html
{% load static %}


<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<body>


<!-- Navbar-->
<nav class="navbar navbar-expand-lg nav-bg">
    <a class="navbar-brand font-white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link font-white" href="#">Current Poll <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class=" font-white nav-link font-white" href="#">Comments</a>
        </li>
        <li class="nav-item dropdown">
          <a class=" font-white nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Past Polls
          </a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <!-- Comment List-->

    <div class="container justify-content-center d-flex pt-4 mb-4">
        <div class = "flex-column d-flex"> 
            <div  class="mb-2 comment-list">
                <h1 class = "font-weight-bold"> Latest Poll: 
                        <block>
                            {{ latest_question.question_text }}
                        </block>
                </h1>
            </div>

            <div class="comment-list">
                <h2> Comments </h2>
            
                <div style>
                    <ol>
                        {% for c in comments %}
                            <li>{{ c.name }}: {{ c.comment_text }}</li>
                        {% endfor %}
                    </ol>
                </div>
          </div>
        </div>
    </div>

    <!-- Footer -->

<div style="position: fixed" class = "mt-5 pt-5 pb-3 footer">
    <div style="color: white" class = "">
      <div class = "d-flex row text-center">

        <div class="col-3">
          <h6>Subscribe to our Newsletter</h6>
          <h6>Learn More</h6>
        </div>

        <div class="col-6">
          <h6>Created by Jett Bisset</h6>
          <p style="font-size: 12px;">All Rights Reserved</p>
        </div>

        <div class="col-3">
          <h6>Privacy</h6>
          <h6>About Us</h6>
        </div>

      </div>
    </div>
  </div>




</body>

polls/templates/polls/question_detail.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<!-- Navbar-->
<nav class="navbar navbar-expand-lg nav-bg">
    <a class="navbar-brand font-white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link font-white" href="#">Current Poll <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class=" font-white nav-link font-white" href="#">Comments</a>
        </li>
        <li class="nav-item dropdown">
          <a class=" font-white nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Past Polls
          </a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

<!-- Question Form-->

<div class="container pt-5 comment-list d-flex flex-column text-center">
    <h1>Poll: {{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
        <input class = "mt-3 btn btn-primary" type="submit" value="Vote">
    </form>

</div>

<!-- Footer -->

<div style="position: fixed" class = "pt-5 pb-3 footer">
    <div style="color: white" class = "">
      <div class = "d-flex row text-center">

        <div class="col-3">
          <h6>Subscribe to our Newsletter</h6>
          <h6>Learn More</h6>
        </div>

        <div class="col-6">
          <h6>Created by Jett Bisset</h6>
          <p style="font-size: 12px;">All Rights Reserved</p>
        </div>

        <div class="col-3">
          <h6>Privacy</h6>
          <h6>About Us</h6>
        </div>

      </div>
    </div>
  </div>

polls/templates/polls/results.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
</head>

<!-- Navbar-->
<nav class="navbar navbar-expand-lg nav-bg">
    <a class="navbar-brand font-white" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link font-white" href="#">Current Poll <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class=" font-white nav-link font-white" href="#">Comments</a>
        </li>
        <li class="nav-item dropdown">
          <a class=" font-white nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Past Polls
          </a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

<!--Results-->
<div class="container pt-5 comment-list text-center"> 
    <h1>{{ question.question_text }}</h1>

    <ul style="list-style: none;" class="pr-5">
    {% for choice in question.choice_set.all %}
        <li class = " text-center result-item">{{ choice.choice_text }}:  {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
    </ul>

    <a class = "mt-3 mr-2 btn btn-primary" href="{% url 'polls:detail' question.id %}">Vote again?</a>
</div>

<!-- Footer -->

<div style="position: fixed" class = "pt-5 pb-3 footer">
    <div style="color: white" class = "">
      <div class = "d-flex row text-center">

        <div class="col-3">
          <h6>Subscribe to our Newsletter</h6>
          <h6>Learn More</h6>
        </div>

        <div class="col-6">
          <h6>Created by Jett Bisset</h6>
          <p style="font-size: 12px;">All Rights Reserved</p>
        </div>

        <div class="col-3">
          <h6>Privacy</h6>
          <h6>About Us</h6>
        </div>

      </div>
    </div>
  </div>